USE [master]
GO
USE[voting_db]
GO
/****** Object:  Database [voting_db]    Script Date: 4/24/2026 1:12:16 PM ******/
CREATE DATABASE [voting_db]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'voting_db', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\voting_db.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'voting_db_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\voting_db_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [voting_db] SET COMPATIBILITY_LEVEL = 170
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [voting_db].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [voting_db] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [voting_db] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [voting_db] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [voting_db] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [voting_db] SET ARITHABORT OFF 
GO
ALTER DATABASE [voting_db] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [voting_db] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [voting_db] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [voting_db] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [voting_db] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [voting_db] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [voting_db] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [voting_db] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [voting_db] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [voting_db] SET  ENABLE_BROKER 
GO
ALTER DATABASE [voting_db] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [voting_db] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [voting_db] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [voting_db] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [voting_db] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [voting_db] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [voting_db] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [voting_db] SET RECOVERY FULL 
GO
ALTER DATABASE [voting_db] SET  MULTI_USER 
GO
ALTER DATABASE [voting_db] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [voting_db] SET DB_CHAINING OFF 
GO
ALTER DATABASE [voting_db] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [voting_db] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [voting_db] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [voting_db] SET OPTIMIZED_LOCKING = OFF 
GO
ALTER DATABASE [voting_db] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'voting_db', N'ON'
GO
ALTER DATABASE [voting_db] SET QUERY_STORE = ON
GO
ALTER DATABASE [voting_db] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [voting_db]
GO
/****** Object:  Table [ballots]    Script Date: 4/24/2026 1:12:16 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [ballots](
	[ballot_id] [int] IDENTITY(1,1) NOT NULL,
	[election_id] [int] NULL,
	[candidate_id] [int] NULL,
	[created_at] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ballot_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [candidates]    Script Date: 4/24/2026 1:12:16 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [candidates](
	[candidate_id] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](100) NULL,
	[party] [varchar](50) NULL,
	[election_id] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[candidate_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [elections]    Script Date: 4/24/2026 1:12:16 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [elections](
	[election_id] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](100) NULL,
	[election_date] [date] NULL,
	[type] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[election_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [users]    Script Date: 4/24/2026 1:12:16 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [users](
	[user_id] [int] IDENTITY(1,1) NOT NULL,
	[username] [varchar](100) NULL,
	[password_hash] [varchar](255) NULL,
	[role] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[user_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [voters]    Script Date: 4/24/2026 1:12:16 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [voters](
	[voter_id] [int] IDENTITY(1,1) NOT NULL,
	[first_name] [varchar](50) NULL,
	[last_name] [varchar](50) NULL,
	[date_of_birth] [date] NULL,
	[address] [text] NULL,
	[registered] [bit] NULL,
	[has_voted] [bit] NULL,
	[user_id] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[voter_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [voting_tokens]    Script Date: 4/24/2026 1:12:16 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [voting_tokens](
	[token_id] [int] IDENTITY(1,1) NOT NULL,
	[voter_id] [int] NULL,
	[election_id] [int] NULL,
	[token_value] [uniqueidentifier] NULL,
	[used] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[token_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[token_value] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [ballots]  WITH CHECK ADD FOREIGN KEY([candidate_id])
REFERENCES [candidates] ([candidate_id])
GO
ALTER TABLE [ballots]  WITH CHECK ADD FOREIGN KEY([election_id])
REFERENCES [elections] ([election_id])
GO
ALTER TABLE [candidates]  WITH CHECK ADD FOREIGN KEY([election_id])
REFERENCES [elections] ([election_id])
GO
ALTER TABLE [voting_tokens]  WITH CHECK ADD FOREIGN KEY([election_id])
REFERENCES [elections] ([election_id])
GO
ALTER TABLE [voting_tokens]  WITH CHECK ADD FOREIGN KEY([voter_id])
REFERENCES [voters] ([voter_id])
GO
USE [master]
GO
ALTER DATABASE [voting_db] SET  READ_WRITE 
GO
